
services:
  animeflix-postgres:
    image: postgres:15
    container_name: animeflix-postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  animeflix-pgadmin:
    image: dpage/pgadmin4
    container_name: animeflix-pgadmin
    restart: always
    depends_on:
      - animeflix-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
